sonar.projectKey=devsecops-project
sonar.projectName=devsecops-project
sonar.host.url=http://localhost:9000
sonar.login=sqp_b92f4ff50020a9a8cf8dca37ac819312aa544153

sonar.sources=app
sonar.python.version=3.12