name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:

  pipeline:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    # SECRET SCAN
    - name: Secret Scan
      uses: zricethezav/gitleaks-action@master

    # BUILD IMAGE
    - name: Build Docker Image
      run: docker build -t myapp:v1 .

    # TRIVY CONTAINER SCAN
    - name: Trivy Scan
      uses: aquasecurity/trivy-action@master

      with:
        image-ref: 'myapp:v1'
        format: 'table'

    # CHECKOV IaC SCAN
    - name: Checkov Scan
      uses: bridgecrewio/checkov-action@master

      with:
        directory: .

    # DEPLOYMENT STAGES
    - name: Deploy to Dev
      run: echo "Deploying to Dev"

    - name: Deploy to Staging
      run: echo "Deploying to Staging"

    - name: Deploy to Production
      run: echo "Deploying to Production"