name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:

  pipeline:
    runs-on: ubuntu-latest

    steps:

    # CHECKOUT CODE
    - name: Checkout
      uses: actions/checkout@v4

    # SECRET SCAN
    - name: Secret Scan
      uses: zricethezav/gitleaks-action@master

    # BUILD DOCKER IMAGE
    - name: Build Docker Image
      run: docker build -t myapp:v1 .

    # TRIVY CONTAINER SCAN
    - name: Trivy Scan
      uses: aquasecurity/trivy-action@master

      with:
        image-ref: 'myapp:v1'
        format: 'table'
        exit-code: '0'

    # CHECKOV IaC SECURITY SCAN
    - name: Checkov Scan
      uses: bridgecrewio/checkov-action@master

      with:
        directory: .
        soft_fail: true

    # DEV DEPLOYMENT
    - name: Deploy to Dev
      run: echo "Deploying to Dev Environment"

    # STAGING DEPLOYMENT
    - name: Deploy to Staging
      run: echo "Deploying to Staging Environment"

    # PRODUCTION DEPLOYMENT
    - name: Deploy to Production
      run: echo "Deploying to Production Environment"